# Generated by Django 3.2.9 on 2022-11-28 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comedor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='horario_final',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='horario',
            name='horario_inicial',
            field=models.DateTimeField(),
        ),
    ]
