# Generated by Django 3.2.9 on 2022-11-28 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comedor', '0002_auto_20221128_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='horario_final',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='horario',
            name='horario_inicial',
            field=models.TimeField(),
        ),
    ]
