# Generated by Django 3.2.9 on 2022-11-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comedor', '0003_auto_20221128_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='Horario',
            field=models.DateField(),
        ),
    ]
